addpath('3rd-party', 'tools')
mapMakerGUI;

% Message Box
fontName = 'FixedWidth';
fontSize = 12;

msg_body = [ ...
    'Welcome to the Simulator!' ...
    char(10) char(10) ...
    'To get started, click on the buttons to input and' ...
    char(10) ...
    'build a custom map using waypoints, landmarks and' ...
    char(10) ...
    'obstacles.' ...
    char(10) char(10) ...
    'This software was modified by Naphish Lashba Raj for a project!' ...
    ];

msg_title = 'Hello!';

msgbox(msg_body, msg_title);